testing possible linters errors
lucianosarno/nytCloneFixingGitHub pull request #1
Opened 2020-06-22 22:10 UTC by lucianosarno

2020-06-23 21:05 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @lucianosarno  and @MohameDawood ! 👋 
Great job with this NYT clone! It looks really good so far👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
- [x] Your pull request has a great title, however, there is no description. **It is extremely important that you add a short description of what you have done in your pull request.** Please add this before requesting for your next review and for **all future reviews.** 

- [x] There is no live demo link in your README file. Please add one. You can generate this using [this link](https://raw.githack.com/).

- [x] The `More in space and astronomy` and `Editor's picks` articles should be wrapped in link tags. 
![Screen Shot 2020-06-23 at 10 56 51 PM](https://user-images.githubusercontent.com/48804258/85461590-d4f03f00-b5a4-11ea-897b-423c81a5228e.png)

- [x] The navigation bar should stick to the top of the screen, yours does not. Please fix this. 
![Screen Shot 2020-06-23 at 11 02 46 PM](https://user-images.githubusercontent.com/48804258/85462346-a9218900-b5a5-11ea-9819-87128c0576aa.png)

- [x] Please remove all commented code. It makes your project look untidy. Please see my comments below. 
![Screen Shot 2020-06-23 at 11 04 56 PM](https://user-images.githubusercontent.com/48804258/85462643-f6055f80-b5a5-11ea-8ec9-d36b92c65007.png)




****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-23 21:06 UTC, BrittanyBlake commented on css/styles.css
> +  width: min-content; /* height: min-content; */
please remove commented code

2020-06-23 21:06 UTC, BrittanyBlake commented on css/styles.css
> +  width: 314px; /* height: 100px; */
please remove commented code

2020-06-23 21:54 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi again @lucianosarno  and @MohameDawood! 👋 
Great job adding a description to your pull request! 👏 👏  This however appears to be the only change that has been made. 
****
Please ensure to read my previous review and make the changes. Here is a shortlist of what was requested:

- [x] Add a live demo link to your Readme file which can be generated using githack.

- [x] Wrap the articles in `More in space and astronomy and editors picks` in `<a>` tags as they are links to other articles.

- [x] Make the navigation bar fixed. 
Your clone 👇 
![Screen Shot 2020-06-23 at 11 50 52 PM](https://user-images.githubusercontent.com/48804258/85468153-60b99980-b5ac-11ea-934d-4518a83e4324.png)
The original page 👇 
![Screen Shot 2020-06-23 at 11 51 17 PM](https://user-images.githubusercontent.com/48804258/85468205-6f07b580-b5ac-11ea-8644-a4e4688a5a49.png)

- [x] There should also be a fixed footer on the page. I'm sorry that I did not point this out to you in the first review, I am not sure how I missed that 🤦🏾‍♀️
The original page 👇 
![Screen Shot 2020-06-23 at 11 53 29 PM](https://user-images.githubusercontent.com/48804258/85468433-be4de600-b5ac-11ea-8c48-b033b67e6c20.png)

Your clone 👇 
![Screen Shot 2020-06-23 at 11 54 09 PM](https://user-images.githubusercontent.com/48804258/85468504-d6256a00-b5ac-11ea-8958-0a9559e56500.png)

- [x] Remove commented code



****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-23 21:55 UTC, BrittanyBlake commented on css/styles.css
> +  width: min-content; /* height: min-content; */
Commented code has not yet been removed

2020-06-23 21:55 UTC, BrittanyBlake commented on css/styles.css
> +  width: 314px; /* height: 100px; */
Commented code has not yet been removed

2020-06-24 21:52 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-24 22:16 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon:

Hi @lucianosarno and @MohameDawood, great job with the fixes :+1: Having fixed all the comments made by the previous TSE, I hereby approve your project. But I will leave an optional comment so you can optionally address. :smile:
[OPTIONAL]
- Kindly add a link to the NYT logo
- Kindly remove all angle tags ``` < ``` in the text, it makes the page unprofessional
- Fix the broken screenshot and address the description of the README. ```M=Dawood``` is not clear to me
- Add margin to the login button

Good luck with your next projects :+1:
_Happy coding_ :code:
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-24 22:48 UTC, merged